[technote]
id = "SITCOMTN-132"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-132.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-132"
github_default_branch = "main"
date_created = 2024-06-19T15:03:13Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Patricio"
name.family = "Cortes"
internal_id = "cortes"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinOpsC"
address = "Rubin Observatory/NSF NOIRLab, Casilla 603, La Serena, Chile"
